### ISSUE TITLE
Translations Build Failure

### ISSUE THREAD

**Issue by hurtstotouchfire** [openedx/credentials#1750]
This will be tracked internally at 2U by https://2u-internal.atlassian.net/browse/APER-1976.

The jobs started failing a few weeks ago. AFAIK, we have not triaged the error to know why they are failing. The original error alert triggered on August 14th. This job has continued to fail each Sunday since the original failure (so a re-run doesn’t look like it will fix the issue).

The logs has an error that looks like:
```
20:18:22 2022-08-14 20:18:22,667 INFO 43769 [utils.py:290] - Opened PR: https://github.com/openedx/credentials/pull/1719
20:18:23 2022-08-14 20:18:23,214 INFO 43769 [utils.py:424] - Deleting branch credentials:transifex-bot-update-translations2022-08-14.
20:18:23 Traceback (most recent call last):
20:18:23   File "transifex/pull.py", line 120, in <module>
20:18:23     pull(
20:18:23   File "transifex/pull.py", line 84, in pull
20:18:23     raise RuntimeError('Failed to compile messages.')
20:18:23 RuntimeError: Failed to compile messages.
```
A link to a failing PR from this job: https://github.com/openedx/credentials/pull/1740 .

Looking at our CI runs I also see an error that looks like:
```
msgfmt: found 1 fatal error

INFO:i18n.validate:Different tags in source and translation
  msgid: Issued {month} {year}
  -----> Emitido {mes}{año}
  -----> "{month}", "{year}" vs "{año}", "{mes}"
```
This looks like we may have had a templated string in Transifex that shouldn’t be translated.

We think this may need to be fixed inside of Transifex.

**Comment by hurtstotouchfire** [comment]
We think this is fixed 🤞
